import { z } from "zod";
import { query } from "@/db";
import { requireAdmin } from "@/lib/admin";
import { audit,clearFailures,loginKey } from "@/lib/account-security";
import { hashPin,randomSalt } from "@/lib/security";
const requestSchema=z.object({companyCode:z.string().trim().min(3).max(20),accountType:z.enum(["Worker","Team"]),identifier:z.string().trim().min(2).max(120)});
const resetSchema=z.object({id:z.number().int().positive(),temporaryCredential:z.string().min(4).max(100)});

export async function POST(request:Request){const p=requestSchema.safeParse(await request.json());if(!p.success)return Response.json({error:"Complete the recovery request."},{status:400});const v=p.data,company=v.companyCode.toUpperCase();const found=v.accountType==="Worker"?await query('SELECT 1 FROM manpower m JOIN companies c ON c.id=m.company_id WHERE c.code=$1 AND m.employee_id=$2 AND m.active=TRUE',[company,v.identifier]):await query('SELECT 1 FROM staff_accounts s JOIN companies c ON c.id=s.company_id WHERE c.code=$1 AND (LOWER(s.email)=LOWER($2) OR LOWER(s.username)=LOWER($2)) AND s.active=TRUE',[company,v.identifier]);if(found.rowCount)await query("INSERT INTO recovery_requests(company_code,account_type,identifier) SELECT $1,$2,$3 WHERE NOT EXISTS(SELECT 1 FROM recovery_requests WHERE company_code=$1 AND account_type=$2 AND LOWER(identifier)=LOWER($3) AND status='Pending')",[company,v.accountType,v.identifier]);return Response.json({ok:true,message:"If the account exists, the company admin will receive your request."},{status:202})}

export async function GET(){const admin=await requireAdmin();if(!admin||admin.role!=="Company Admin")return Response.json({error:"Company admin access required."},{status:403});const code=admin.companyId?(await query("SELECT code FROM companies WHERE id=$1",[admin.companyId])).rows[0]?.code:null;const sql='SELECT id,company_code AS "companyCode",account_type AS "accountType",identifier,status,requested_at AS "requestedAt" FROM recovery_requests WHERE status=\'Pending\'';const r=code?await query(`${sql} AND company_code=$1 ORDER BY id DESC LIMIT 100`,[code]):await query(`${sql} ORDER BY id DESC LIMIT 100`);return Response.json(r.rows)}

export async function PATCH(request:Request){const admin=await requireAdmin();if(!admin||admin.role!=="Company Admin")return Response.json({error:"Company admin access required."},{status:403});const p=resetSchema.safeParse(await request.json());if(!p.success)return Response.json({error:"Provide a temporary PIN or password."},{status:400});const req=await query<{id:number;companyCode:string;accountType:string;identifier:string}>('SELECT id,company_code AS "companyCode",account_type AS "accountType",identifier FROM recovery_requests WHERE id=$1 AND status=$2',[p.data.id,"Pending"]),row=req.rows[0];if(!row)return Response.json({error:"Recovery request is no longer pending."},{status:404});if(admin.companyId){const own=await query("SELECT 1 FROM companies WHERE id=$1 AND code=$2",[admin.companyId,row.companyCode]);if(!own.rowCount)return Response.json({error:"Recovery request is outside your company."},{status:403})}const salt=randomSalt(),hash=await hashPin(p.data.temporaryCredential,salt);if(row.accountType==="Worker"){if(!/^\d{4,8}$/.test(p.data.temporaryCredential))return Response.json({error:"Worker PIN must contain 4–8 digits."},{status:400});await query('UPDATE manpower m SET pin_salt=$1,pin_hash=$2,must_change_pin=TRUE FROM companies c WHERE m.company_id=c.id AND c.code=$3 AND m.employee_id=$4',[salt,hash,row.companyCode,row.identifier]);await clearFailures(loginKey("worker",row.companyCode,row.identifier))}else{if(p.data.temporaryCredential.length<8)return Response.json({error:"Team password must be at least 8 characters."},{status:400});await query('UPDATE staff_accounts s SET password_salt=$1,password_hash=$2,must_change_password=TRUE FROM companies c WHERE s.company_id=c.id AND c.code=$3 AND (LOWER(s.email)=LOWER($4) OR LOWER(s.username)=LOWER($4))',[salt,hash,row.companyCode,row.identifier]);await clearFailures(loginKey("staff",row.companyCode,row.identifier))}await query("UPDATE recovery_requests SET status='Resolved',resolved_at=NOW(),resolved_by=$1 WHERE id=$2",[admin.email,row.id]);await audit({companyId:admin.companyId,actorType:admin.role,actorId:admin.email,action:"RESET_CREDENTIAL",entityType:row.accountType,entityId:row.identifier,summary:`Reset ${row.accountType.toLowerCase()} credential`});return Response.json({ok:true})}
