"use client";
import { FormEvent,useState } from "react";
import { Building2,HardHat } from "lucide-react";

export default function RegisterCompany(){
 const [error,setError]=useState(""),[busy,setBusy]=useState(false),[code,setCode]=useState("");
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const r=await fetch("/api/company/register",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))}),out=await r.json();setBusy(false);if(!r.ok)return setError(out.error);setCode(out.companyCode)}
 return <div className="loginpage"><section className="loginbox"><div className="brand dark"><span><HardHat/></span><div><b>Workforce Hub Lite</b><small>COMPANY SETUP</small></div></div>{code?<><h1>Company created</h1><p>Save this code. Every administrator, manager and worker will use it to sign in.</p><span className="company-code">Company code<br/><b>{code}</b></span><a className="primary" href="/admin">Continue to team sign in</a></>:<><h1>Register your company</h1><p>This creates an isolated company workspace and its first administrator.</p>{error&&<div className="formerror">{error}</div>}<form onSubmit={submit}><label className="field"><span>Company name</span><input name="companyName" required/></label><label className="field"><span>Administrator name</span><input name="adminName" required/></label><label className="field"><span>Administrator username</span><input name="username" autoComplete="username" required/></label><label className="field"><span>Email</span><input name="email" type="email" required/></label><label className="field"><span>Password</span><input name="password" type="password" minLength={8} autoComplete="new-password" required/></label><button className="primary" disabled={busy}><Building2/>{busy?"Creating company…":"Create company & code"}</button></form><a href="/admin">Back to team sign in</a></>}</section></div>
}
