import { z } from "zod";
import { requireAdmin } from "@/lib/admin";
import { hashPin,randomSalt } from "@/lib/security";
import { pool,query } from "@/db";
import { audit } from "@/lib/account-security";

const schema=z.object({name:z.string().trim().min(2).max(100),username:z.string().trim().min(2).max(50).regex(/^[A-Za-z0-9._-]+$/),email:z.string().email(),role:z.enum(["Company Admin","Manager","Supervisor","HR","Safety Officer"]),scopeType:z.enum(["Company","Plant","Department","Sub-department","Discipline"]),scopeId:z.number().int().positive().nullable(),password:z.string().min(8).max(100),employeeId:z.string().trim().max(30).optional().default(""),workerPin:z.string().trim().optional().default(""),shift:z.enum(["A","B","C","G"]).optional().default("G")});

async function companyIdFor(admin:Awaited<ReturnType<typeof requireAdmin>>){return admin?.companyId||(await query("SELECT id FROM companies ORDER BY id LIMIT 1")).rows[0]?.id}

export async function GET(){const admin=await requireAdmin();if(!admin||admin.role!=="Company Admin")return Response.json({error:"Company admin access required."},{status:403});const companyId=await companyIdFor(admin);const r=await query('SELECT s.id,s.name,s.username,s.email,s.role,s.scope_type AS "scopeType",s.scope_id AS "scopeId",s.manpower_id AS "manpowerId",u.name AS "scopeName",s.active FROM staff_accounts s LEFT JOIN organization_units u ON u.id=s.scope_id WHERE s.company_id=$1 ORDER BY s.id DESC',[companyId]);return Response.json(r.rows)}

export async function POST(request:Request){
 const admin=await requireAdmin();if(!admin||admin.role!=="Company Admin")return Response.json({error:"Company admin access required."},{status:403});
 const p=schema.safeParse(await request.json());if(!p.success)return Response.json({error:"Complete the account fields. Username may use letters, numbers, dots, dashes and underscores."},{status:400});
 const v=p.data;if(v.scopeType!=="Company"&&!v.scopeId)return Response.json({error:"Choose an organization scope."},{status:400});if((v.employeeId&&!/^\S{2,30}$/.test(v.employeeId))||(v.workerPin&&!/^\d{4,8}$/.test(v.workerPin)))return Response.json({error:"Self-service requires an Employee ID and a 4–8 digit PIN."},{status:400});if(Boolean(v.employeeId)!==Boolean(v.workerPin))return Response.json({error:"Enter both self-service Employee ID and PIN, or leave both blank."},{status:400});
 const companyId=await companyIdFor(admin),salt=randomSalt(),hash=await hashPin(v.password,salt),client=await pool.connect();
 try{await client.query("BEGIN");const staff=await client.query('INSERT INTO staff_accounts(company_id,username,email,name,role,scope_type,scope_id,password_salt,password_hash) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING id',[companyId,v.username.toLowerCase(),v.email.toLowerCase(),v.name,v.role,v.scopeType,v.scopeId,salt,hash]);if(v.employeeId){const pinSalt=randomSalt(),pinHash=await hashPin(v.workerPin,pinSalt),worker=await client.query('INSERT INTO manpower(employee_id,name,contractor,trade,skill_level,shift,pin_salt,pin_hash,active,company_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,TRUE,$9) RETURNING id',[v.employeeId,v.name,"Company Staff",v.role,"Certified",v.shift,pinSalt,pinHash,companyId]);await client.query("UPDATE staff_accounts SET manpower_id=$1 WHERE id=$2",[worker.rows[0].id,staff.rows[0].id])}await client.query("COMMIT");await audit({companyId:Number(companyId),actorType:admin.role,actorId:admin.email,action:"CREATE",entityType:"Staff account",entityId:v.username,summary:`Created ${v.role} account`});return Response.json({ok:true},{status:201})}catch(e){await client.query("ROLLBACK");return Response.json({error:String(e).includes("23505")?"That username, email or Employee ID is already in use.":"Unable to create account."},{status:400})}finally{client.release()}
}
